"""forge training tables

Revision ID: 03afc2a09747
Revises: 2432b644e9fc
Create Date: 2026-07-18 21:01:18.309591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03afc2a09747'
down_revision: Union[str, Sequence[str], None] = '2432b644e9fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('primary_muscle', sa.String(), nullable=False),
    sa.Column('secondary_muscles', sa.JSON(), nullable=False),
    sa.Column('equipment', sa.String(), nullable=False),
    sa.Column('movement_pattern', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('contraindications', sa.JSON(), nullable=False),
    sa.Column('cue', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_exercises_primary_muscle'), 'exercises', ['primary_muscle'], unique=False)
    op.create_table('physique_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reference_label', sa.String(), nullable=False),
    sa.Column('reference_image_path', sa.String(), nullable=True),
    sa.Column('gap_report', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('superseded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_physique_goals_user_id'), 'physique_goals', ['user_id'], unique=False)
    op.create_table('progress_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('taken_at', sa.Date(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_photos_user_id'), 'progress_photos', ['user_id'], unique=False)
    op.create_table('workout_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('split_type', sa.String(), nullable=False),
    sa.Column('days_per_week', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('spine_conscious', sa.Boolean(), nullable=False),
    sa.Column('equipment', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['goal_id'], ['physique_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_programs_user_id'), 'workout_programs', ['user_id'], unique=False)
    op.create_table('program_days',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('day_label', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['workout_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_days_program_id'), 'program_days', ['program_id'], unique=False)
    op.create_table('program_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_day_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=False),
    sa.Column('rep_low', sa.Integer(), nullable=False),
    sa.Column('rep_high', sa.Integer(), nullable=False),
    sa.Column('target_rir', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('consecutive_misses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_program_exercises_program_day_id'), 'program_exercises', ['program_day_id'], unique=False)
    op.create_table('workout_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_day_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['program_day_id'], ['program_days.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_sessions_user_id'), 'workout_sessions', ['user_id'], unique=False)
    op.create_table('set_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('program_exercise_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rir', sa.Integer(), nullable=True),
    sa.Column('is_amrap', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['program_exercise_id'], ['program_exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['workout_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_set_logs_program_exercise_id'), 'set_logs', ['program_exercise_id'], unique=False)
    op.create_index(op.f('ix_set_logs_session_id'), 'set_logs', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_set_logs_session_id'), table_name='set_logs')
    op.drop_index(op.f('ix_set_logs_program_exercise_id'), table_name='set_logs')
    op.drop_table('set_logs')
    op.drop_index(op.f('ix_workout_sessions_user_id'), table_name='workout_sessions')
    op.drop_table('workout_sessions')
    op.drop_index(op.f('ix_program_exercises_program_day_id'), table_name='program_exercises')
    op.drop_table('program_exercises')
    op.drop_index(op.f('ix_program_days_program_id'), table_name='program_days')
    op.drop_table('program_days')
    op.drop_index(op.f('ix_workout_programs_user_id'), table_name='workout_programs')
    op.drop_table('workout_programs')
    op.drop_index(op.f('ix_progress_photos_user_id'), table_name='progress_photos')
    op.drop_table('progress_photos')
    op.drop_index(op.f('ix_physique_goals_user_id'), table_name='physique_goals')
    op.drop_table('physique_goals')
    op.drop_index(op.f('ix_exercises_primary_muscle'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
